name: CI Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  validation:
    name: Translation validation
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: "20"

      - name: Validate translations
        run: node .github/ci-validateTranslations.js

      - name: Check translation keys
        run: node .github/ci-checkTranslationKeys.js
