- name: "Run OSSF Scorecard Analysis"
  uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
  with:
    results_file: results.sarif
    results_format: sarif
    publish_results: true
