name: Update Advanced Settings Markdown TOC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 29 2 1'

permissions: read-all

jobs:
  update-toc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: ${{github.repository}}.wiki
      - name: Run github-markdown-toc
        run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup Advanced-Settings.md
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: "Auto update markdown TOC"
