name: Validate translations

on:
  push:
    branches:
      - develop
    paths:
      - ".github/ci-checkTranslationKeys.js"
      - ".github/ci-validateTranslations.js"
      - "index.html"
      - "main.js"
      - "translations/translate.js"
      - "translations/*.json"
  pull_request:
    branches:
      - develop
    paths:
      - ".github/ci-checkTranslationKeys.js"
      - ".github/ci-validateTranslations.js"
      - "index.html"
      - "main.js"
      - "translations/translate.js"
      - "translations/*.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: "20"

      - name: Validate translations
        run: node .github/ci-validateTranslations.js

      - name: Check translation keys
        run: node .github/ci-checkTranslationKeys.js
